"""add intervals

Revision ID: aeb5a1c9daf9
Revises: 331e816ac346
Create Date: 2024-04-18 14:23:56.230770

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.sql import text
from sqlalchemy import orm

from core.models import Interval

# revision identifiers, used by Alembic.
revision: str = "aeb5a1c9daf9"
down_revision: Union[str, None] = "331e816ac346"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    intervals = [
        Interval(value="1 week"),
        Interval(value="2 weeks"),
        Interval(value="4 weeks"),
        Interval(value="1 month"),
        Interval(value="3 months"),
        Interval(value="6 months"),
        Interval(value="1 year"),
    ]

    session.add_all(intervals)
    session.commit()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for interval in session.query(Interval):
        session.delete(interval)
    session.commit()
    bind.execute(text("alter sequence intervals_id_seq restart with 1"))
    # ### end Alembic commands ###
