"""add current_interval column in users table

Revision ID: 5ed75c69b5bf
Revises: e0cb5aeddcd9
Create Date: 2024-04-19 21:42:33.106796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ed75c69b5bf"
down_revision: Union[str, None] = "e0cb5aeddcd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("current_interval", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "current_interval_fkey", "users", "intervals", ["current_interval"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("current_interval_fkey", "users", type_="foreignkey")
    op.drop_column("users", "current_interval")
    # ### end Alembic commands ###
