"""fix amount field in records and plannings

Revision ID: 13ccb771f425
Revises: 8299b061888c
Create Date: 2024-06-11 17:42:15.120212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13ccb771f425"
down_revision: Union[str, None] = "8299b061888c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("plannings", "amount", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("records", "amount", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("records", "amount", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("plannings", "amount", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
