"""fix amount field in records and plannings

Revision ID: 11ecf15a72b3
Revises: 13ccb771f425
Create Date: 2024-06-12 17:06:43.809561

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11ecf15a72b3"
down_revision: Union[str, None] = "13ccb771f425"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records",
        sa.Column(
            "date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_constraint("records_period_id_fkey", "records", type_="foreignkey")
    op.drop_column("records", "period_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records",
        sa.Column("period_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "records_period_id_fkey", "records", "periods", ["period_id"], ["id"]
    )
    op.drop_column("records", "date")
    # ### end Alembic commands ###
