"""create category table

Revision ID: 0821b468aaf2
Revises: b95bb5f4f392
Create Date: 2024-04-15 21:24:40.443125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0821b468aaf2"
down_revision: Union[str, None] = "b95bb5f4f392"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "income",
                "outcome",
                "savings",
                name="category_type",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("categories")
    sa.Enum(
        "income",
        "outcome",
        "savings",
        name="category_type",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
