"""add interval_id column in period table

Revision ID: e0cb5aeddcd9
Revises: b788d862ddb9
Create Date: 2024-04-19 21:31:35.054399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0cb5aeddcd9"
down_revision: Union[str, None] = "b788d862ddb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("periods", sa.Column("interval_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "interval_id_fkey", "periods", "intervals", ["interval_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("interval_id_fkey", "periods", type_="foreignkey")
    op.drop_column("periods", "interval_id")
    # ### end Alembic commands ###
