"""update record model

Revision ID: da6ad32256a1
Revises: 5ed75c69b5bf
Create Date: 2024-06-10 15:37:51.039441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da6ad32256a1"
down_revision: Union[str, None] = "5ed75c69b5bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("amount", sa.Integer(), nullable=True))
    op.drop_column("records", "fact")
    op.drop_column("records", "plan")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records", sa.Column("plan", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "records", sa.Column("fact", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("records", "amount")
    # ### end Alembic commands ###
